# Generated by Django 4.2.19 on 2025-02-19 02:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('song_title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoirMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_part', models.CharField(blank=True, choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bass 1'), ('B2', 'Bass 2')], max_length=2, null=True)),
                ('folder_number', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RosterApplication_choirmember',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('will_attend', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RosterApplication.choirmember')),
            ],
        ),
    ]
