# Generated by Django 4.2.9 on 2025-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosterApplication', '0003_unreadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='choirmember',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
